// <auto-generated />
using CASESTUDY.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CASESTUDY.Migrations.SubCategory
{
    [DbContext(typeof(SubCategoryContext))]
    [Migration("20200201092914_InitialCreate1")]
    partial class InitialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CASESTUDY.Models.SubCategory", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brief_Details1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brief_details2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GST_Percentage")
                        .HasColumnType("real");

                    b.Property<int>("Subcategory_id")
                        .HasColumnType("int");

                    b.Property<string>("Subcategory_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_id");

                    b.ToTable("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
